// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/aaronzjc/mu/internal/application/dto"
	mock "github.com/stretchr/testify/mock"
)

// FavorService is an autogenerated mock type for the FavorService type
type FavorService struct {
	mock.Mock
}

type FavorService_Expecter struct {
	mock *mock.Mock
}

func (_m *FavorService) EXPECT() *FavorService_Expecter {
	return &FavorService_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: _a0, _a1
func (_m *FavorService) Add(_a0 context.Context, _a1 *dto.Favor) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.Favor) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FavorService_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type FavorService_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *dto.Favor
func (_e *FavorService_Expecter) Add(_a0 interface{}, _a1 interface{}) *FavorService_Add_Call {
	return &FavorService_Add_Call{Call: _e.mock.On("Add", _a0, _a1)}
}

func (_c *FavorService_Add_Call) Run(run func(_a0 context.Context, _a1 *dto.Favor)) *FavorService_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.Favor))
	})
	return _c
}

func (_c *FavorService_Add_Call) Return(_a0 error) *FavorService_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetUserFavorSites provides a mock function with given fields: _a0, _a1, _a2
func (_m *FavorService) GetUserFavorSites(_a0 context.Context, _a1 int, _a2 string) ([]string, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context, int, string) []string); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FavorService_GetUserFavorSites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserFavorSites'
type FavorService_GetUserFavorSites_Call struct {
	*mock.Call
}

// GetUserFavorSites is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int
//   - _a2 string
func (_e *FavorService_Expecter) GetUserFavorSites(_a0 interface{}, _a1 interface{}, _a2 interface{}) *FavorService_GetUserFavorSites_Call {
	return &FavorService_GetUserFavorSites_Call{Call: _e.mock.On("GetUserFavorSites", _a0, _a1, _a2)}
}

func (_c *FavorService_GetUserFavorSites_Call) Run(run func(_a0 context.Context, _a1 int, _a2 string)) *FavorService_GetUserFavorSites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *FavorService_GetUserFavorSites_Call) Return(_a0 []string, _a1 error) *FavorService_GetUserFavorSites_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetUserFavors provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *FavorService) GetUserFavors(_a0 context.Context, _a1 int, _a2 string, _a3 string) ([]*dto.Favor, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 []*dto.Favor
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) []*dto.Favor); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.Favor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FavorService_GetUserFavors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserFavors'
type FavorService_GetUserFavors_Call struct {
	*mock.Call
}

// GetUserFavors is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int
//   - _a2 string
//   - _a3 string
func (_e *FavorService_Expecter) GetUserFavors(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *FavorService_GetUserFavors_Call {
	return &FavorService_GetUserFavors_Call{Call: _e.mock.On("GetUserFavors", _a0, _a1, _a2, _a3)}
}

func (_c *FavorService_GetUserFavors_Call) Run(run func(_a0 context.Context, _a1 int, _a2 string, _a3 string)) *FavorService_GetUserFavors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *FavorService_GetUserFavors_Call) Return(_a0 []*dto.Favor, _a1 error) *FavorService_GetUserFavors_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Remove provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *FavorService) Remove(_a0 context.Context, _a1 int, _a2 string, _a3 string) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FavorService_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type FavorService_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int
//   - _a2 string
//   - _a3 string
func (_e *FavorService_Expecter) Remove(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *FavorService_Remove_Call {
	return &FavorService_Remove_Call{Call: _e.mock.On("Remove", _a0, _a1, _a2, _a3)}
}

func (_c *FavorService_Remove_Call) Run(run func(_a0 context.Context, _a1 int, _a2 string, _a3 string)) *FavorService_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *FavorService_Remove_Call) Return(_a0 error) *FavorService_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewFavorService interface {
	mock.TestingT
	Cleanup(func())
}

// NewFavorService creates a new instance of FavorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFavorService(t mockConstructorTestingTNewFavorService) *FavorService {
	mock := &FavorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
