// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NodeService is an autogenerated mock type for the NodeService type
type NodeService struct {
	mock.Mock
}

type NodeService_Expecter struct {
	mock *mock.Mock
}

func (_m *NodeService) EXPECT() *NodeService_Expecter {
	return &NodeService_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewNodeService interface {
	mock.TestingT
	Cleanup(func())
}

// NewNodeService creates a new instance of NodeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNodeService(t mockConstructorTestingTNewNodeService) *NodeService {
	mock := &NodeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
