// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cron.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cron struct {
	Site                 string   `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cron) Reset()         { *m = Cron{} }
func (m *Cron) String() string { return proto.CompactTextString(m) }
func (*Cron) ProtoMessage()    {}
func (*Cron) Descriptor() ([]byte, []int) {
	return fileDescriptor_21379dc2cd81a5b8, []int{0}
}

func (m *Cron) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cron.Unmarshal(m, b)
}
func (m *Cron) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cron.Marshal(b, m, deterministic)
}
func (m *Cron) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cron.Merge(m, src)
}
func (m *Cron) XXX_Size() int {
	return xxx_messageInfo_Cron.Size(m)
}
func (m *Cron) XXX_DiscardUnknown() {
	xxx_messageInfo_Cron.DiscardUnknown(m)
}

var xxx_messageInfo_Cron proto.InternalMessageInfo

func (m *Cron) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_21379dc2cd81a5b8, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type CronRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CronRes) Reset()         { *m = CronRes{} }
func (m *CronRes) String() string { return proto.CompactTextString(m) }
func (*CronRes) ProtoMessage()    {}
func (*CronRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_21379dc2cd81a5b8, []int{2}
}

func (m *CronRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CronRes.Unmarshal(m, b)
}
func (m *CronRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CronRes.Marshal(b, m, deterministic)
}
func (m *CronRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CronRes.Merge(m, src)
}
func (m *CronRes) XXX_Size() int {
	return xxx_messageInfo_CronRes.Size(m)
}
func (m *CronRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CronRes.DiscardUnknown(m)
}

var xxx_messageInfo_CronRes proto.InternalMessageInfo

func (m *CronRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DebugRes struct {
	Res                  string   `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebugRes) Reset()         { *m = DebugRes{} }
func (m *DebugRes) String() string { return proto.CompactTextString(m) }
func (*DebugRes) ProtoMessage()    {}
func (*DebugRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_21379dc2cd81a5b8, []int{3}
}

func (m *DebugRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugRes.Unmarshal(m, b)
}
func (m *DebugRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugRes.Marshal(b, m, deterministic)
}
func (m *DebugRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugRes.Merge(m, src)
}
func (m *DebugRes) XXX_Size() int {
	return xxx_messageInfo_DebugRes.Size(m)
}
func (m *DebugRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugRes.DiscardUnknown(m)
}

var xxx_messageInfo_DebugRes proto.InternalMessageInfo

func (m *DebugRes) GetRes() string {
	if m != nil {
		return m.Res
	}
	return ""
}

func init() {
	proto.RegisterType((*Cron)(nil), "rpc.Cron")
	proto.RegisterType((*Empty)(nil), "rpc.Empty")
	proto.RegisterType((*CronRes)(nil), "rpc.CronRes")
	proto.RegisterType((*DebugRes)(nil), "rpc.DebugRes")
}

func init() { proto.RegisterFile("cron.proto", fileDescriptor_21379dc2cd81a5b8) }

var fileDescriptor_21379dc2cd81a5b8 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xc1, 0x0a, 0x82, 0x40,
	0x10, 0x86, 0x15, 0x35, 0x75, 0x28, 0x88, 0x3d, 0x89, 0x74, 0x88, 0x2d, 0xa8, 0x93, 0x87, 0x7a,
	0x04, 0xeb, 0x05, 0x16, 0xba, 0x74, 0xd3, 0x75, 0x88, 0x0e, 0xba, 0xcb, 0xce, 0x7a, 0xe8, 0xed,
	0x63, 0x87, 0xec, 0xf6, 0x0d, 0xf3, 0xf1, 0xff, 0x33, 0x00, 0xda, 0x99, 0xa9, 0xb1, 0xce, 0x78,
	0x23, 0x12, 0x67, 0xb5, 0xac, 0x21, 0x6d, 0x9d, 0x99, 0x84, 0x80, 0x94, 0xde, 0x1e, 0xab, 0x78,
	0x1f, 0x9f, 0x4b, 0xc5, 0x2c, 0x73, 0xc8, 0xee, 0xa3, 0xf5, 0x1f, 0x79, 0x80, 0x3c, 0x48, 0x0a,
	0x49, 0x54, 0x90, 0xd3, 0xac, 0x35, 0x12, 0xb1, 0x5a, 0xa8, 0x65, 0x94, 0x3b, 0x28, 0x6e, 0xd8,
	0xcf, 0xaf, 0x60, 0x6d, 0x21, 0x71, 0x48, 0xbf, 0xb0, 0x80, 0x97, 0x27, 0x94, 0xad, 0x19, 0xc7,
	0x6e, 0x1a, 0xd0, 0x89, 0x13, 0xc0, 0xc3, 0x0e, 0x9d, 0x47, 0xae, 0x2e, 0x1b, 0x67, 0x75, 0x13,
	0xb0, 0x5e, 0xff, 0x51, 0x21, 0xc9, 0x48, 0x1c, 0x21, 0xe3, 0x4c, 0x01, 0xbc, 0xe0, 0x6b, 0xea,
	0x0d, 0xf3, 0xd2, 0x25, 0xa3, 0x7e, 0xc5, 0xff, 0x5c, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x32,
	0xd4, 0x6d, 0xad, 0xdd, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommanderClient is the client API for Commander service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommanderClient interface {
	UpdateCron(ctx context.Context, in *Cron, opts ...grpc.CallOption) (*CronRes, error)
	Debug(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DebugRes, error)
}

type commanderClient struct {
	cc *grpc.ClientConn
}

func NewCommanderClient(cc *grpc.ClientConn) CommanderClient {
	return &commanderClient{cc}
}

func (c *commanderClient) UpdateCron(ctx context.Context, in *Cron, opts ...grpc.CallOption) (*CronRes, error) {
	out := new(CronRes)
	err := c.cc.Invoke(ctx, "/rpc.Commander/UpdateCron", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commanderClient) Debug(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DebugRes, error) {
	out := new(DebugRes)
	err := c.cc.Invoke(ctx, "/rpc.Commander/Debug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommanderServer is the server API for Commander service.
type CommanderServer interface {
	UpdateCron(context.Context, *Cron) (*CronRes, error)
	Debug(context.Context, *Empty) (*DebugRes, error)
}

// UnimplementedCommanderServer can be embedded to have forward compatible implementations.
type UnimplementedCommanderServer struct {
}

func (*UnimplementedCommanderServer) UpdateCron(ctx context.Context, req *Cron) (*CronRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCron not implemented")
}
func (*UnimplementedCommanderServer) Debug(ctx context.Context, req *Empty) (*DebugRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Debug not implemented")
}

func RegisterCommanderServer(s *grpc.Server, srv CommanderServer) {
	s.RegisterService(&_Commander_serviceDesc, srv)
}

func _Commander_UpdateCron_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cron)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommanderServer).UpdateCron(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Commander/UpdateCron",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommanderServer).UpdateCron(ctx, req.(*Cron))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commander_Debug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommanderServer).Debug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Commander/Debug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommanderServer).Debug(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Commander_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Commander",
	HandlerType: (*CommanderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateCron",
			Handler:    _Commander_UpdateCron_Handler,
		},
		{
			MethodName: "Debug",
			Handler:    _Commander_Debug_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cron.proto",
}
