// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Result struct {
	Map                  map[string]*Result_HotList `protobuf:"bytes,1,rep,name=Map,proto3" json:"Map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	T                    string                     `protobuf:"bytes,2,opt,name=T,proto3" json:"T,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetMap() map[string]*Result_HotList {
	if m != nil {
		return m.Map
	}
	return nil
}

func (m *Result) GetT() string {
	if m != nil {
		return m.T
	}
	return ""
}

type Result_HotList struct {
	Item                 []*Result_HotList_Item `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Result_HotList) Reset()         { *m = Result_HotList{} }
func (m *Result_HotList) String() string { return proto.CompactTextString(m) }
func (*Result_HotList) ProtoMessage()    {}
func (*Result_HotList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{1, 0}
}

func (m *Result_HotList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result_HotList.Unmarshal(m, b)
}
func (m *Result_HotList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result_HotList.Marshal(b, m, deterministic)
}
func (m *Result_HotList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result_HotList.Merge(m, src)
}
func (m *Result_HotList) XXX_Size() int {
	return xxx_messageInfo_Result_HotList.Size(m)
}
func (m *Result_HotList) XXX_DiscardUnknown() {
	xxx_messageInfo_Result_HotList.DiscardUnknown(m)
}

var xxx_messageInfo_Result_HotList proto.InternalMessageInfo

func (m *Result_HotList) GetItem() []*Result_HotList_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type Result_HotList_Item struct {
	Title                string   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Rank                 float32  `protobuf:"fixed32,2,opt,name=Rank,proto3" json:"Rank,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=Url,proto3" json:"Url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result_HotList_Item) Reset()         { *m = Result_HotList_Item{} }
func (m *Result_HotList_Item) String() string { return proto.CompactTextString(m) }
func (*Result_HotList_Item) ProtoMessage()    {}
func (*Result_HotList_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{1, 0, 0}
}

func (m *Result_HotList_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result_HotList_Item.Unmarshal(m, b)
}
func (m *Result_HotList_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result_HotList_Item.Marshal(b, m, deterministic)
}
func (m *Result_HotList_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result_HotList_Item.Merge(m, src)
}
func (m *Result_HotList_Item) XXX_Size() int {
	return xxx_messageInfo_Result_HotList_Item.Size(m)
}
func (m *Result_HotList_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Result_HotList_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Result_HotList_Item proto.InternalMessageInfo

func (m *Result_HotList_Item) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Result_HotList_Item) GetRank() float32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *Result_HotList_Item) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*Job)(nil), "rpc.Job")
	proto.RegisterType((*Result)(nil), "rpc.Result")
	proto.RegisterMapType((map[string]*Result_HotList)(nil), "rpc.Result.MapEntry")
	proto.RegisterType((*Result_HotList)(nil), "rpc.Result.HotList")
	proto.RegisterType((*Result_HotList_Item)(nil), "rpc.Result.HotList.Item")
}

func init() { proto.RegisterFile("job.proto", fileDescriptor_f32c477d91a04ead) }

var fileDescriptor_f32c477d91a04ead = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x4d, 0xd3, 0xcd, 0xed, 0xd5, 0x83, 0x3c, 0x77, 0x88, 0xbd, 0x38, 0x7a, 0x90, 0x0a,
	0x92, 0x43, 0xbd, 0x88, 0x37, 0x15, 0x41, 0xa7, 0xbb, 0x84, 0xfa, 0x01, 0xd2, 0x11, 0xa4, 0xae,
	0x6d, 0x42, 0x96, 0x29, 0xc3, 0x2f, 0xe0, 0xc7, 0x96, 0xa4, 0x1d, 0xec, 0xe0, 0xed, 0xff, 0x78,
	0xbf, 0xf7, 0xcb, 0x9f, 0xc0, 0xf4, 0x53, 0x57, 0xdc, 0x58, 0xed, 0x34, 0x52, 0x6b, 0x56, 0xd9,
	0x39, 0xd0, 0x85, 0xae, 0x10, 0x21, 0xee, 0x64, 0xab, 0x18, 0x99, 0x93, 0x7c, 0x2a, 0x42, 0xce,
	0x7e, 0x23, 0x18, 0x0b, 0xb5, 0xd9, 0x36, 0x0e, 0x2f, 0x81, 0x2e, 0xa5, 0x61, 0x64, 0x4e, 0xf3,
	0xa4, 0x98, 0x71, 0x6b, 0x56, 0xbc, 0xdf, 0xf0, 0xa5, 0x34, 0x4f, 0x9d, 0xb3, 0x3b, 0xe1, 0x01,
	0x3c, 0x01, 0x52, 0xb2, 0x28, 0x38, 0x48, 0x99, 0xfe, 0xc0, 0xf1, 0xb3, 0x76, 0x6f, 0xf5, 0xc6,
	0xe1, 0x35, 0xc4, 0xb5, 0x53, 0xed, 0x60, 0x60, 0x87, 0x86, 0x01, 0xe1, 0x2f, 0x4e, 0xb5, 0x22,
	0x50, 0xe9, 0x03, 0xc4, 0x7e, 0xc2, 0x19, 0x8c, 0xca, 0xda, 0x35, 0xfb, 0x5a, 0xfd, 0xe0, 0xbb,
	0x0a, 0xd9, 0xad, 0xc3, 0x3b, 0x91, 0x08, 0x19, 0x4f, 0x81, 0xbe, 0xdb, 0x86, 0xd1, 0xc0, 0xf9,
	0x98, 0xbe, 0xc2, 0x64, 0xdf, 0xcd, 0x6f, 0xd7, 0x6a, 0x37, 0x58, 0x7c, 0xc4, 0x2b, 0x18, 0x7d,
	0xc9, 0x66, 0xab, 0x82, 0x24, 0x29, 0xce, 0xfe, 0x29, 0x24, 0x7a, 0xe2, 0x2e, 0xba, 0x25, 0x45,
	0x0e, 0xa3, 0xfb, 0x0f, 0xd5, 0x39, 0xbc, 0x80, 0xf8, 0xd1, 0xca, 0x6f, 0x9c, 0x84, 0x83, 0x85,
	0xae, 0xd2, 0xe4, 0xe0, 0x34, 0x3b, 0xaa, 0xc6, 0xe1, 0x6f, 0x6f, 0xfe, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x55, 0x9f, 0xd0, 0x2d, 0x68, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	Craw(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Result, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Craw(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/rpc.Agent/Craw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	Craw(context.Context, *Job) (*Result, error)
}

// UnimplementedAgentServer can be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (*UnimplementedAgentServer) Craw(ctx context.Context, req *Job) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Craw not implemented")
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_Craw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Craw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Agent/Craw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Craw(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Craw",
			Handler:    _Agent_Craw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job.proto",
}
