// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ping struct {
	Ping                 string   `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

type Pong struct {
	Pong                 string   `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

type Job struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Headers              []*Job_Header `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{2}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Job) GetHeaders() []*Job_Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

type Job_Header struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Val                  string   `protobuf:"bytes,2,opt,name=Val,proto3" json:"Val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job_Header) Reset()         { *m = Job_Header{} }
func (m *Job_Header) String() string { return proto.CompactTextString(m) }
func (*Job_Header) ProtoMessage()    {}
func (*Job_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{2, 0}
}

func (m *Job_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job_Header.Unmarshal(m, b)
}
func (m *Job_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job_Header.Marshal(b, m, deterministic)
}
func (m *Job_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job_Header.Merge(m, src)
}
func (m *Job_Header) XXX_Size() int {
	return xxx_messageInfo_Job_Header.Size(m)
}
func (m *Job_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Job_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Job_Header proto.InternalMessageInfo

func (m *Job_Header) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Job_Header) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

type Result struct {
	HotMap               map[string]string `protobuf:"bytes,1,rep,name=HotMap,proto3" json:"HotMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	T                    string            `protobuf:"bytes,2,opt,name=T,proto3" json:"T,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{3}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetHotMap() map[string]string {
	if m != nil {
		return m.HotMap
	}
	return nil
}

func (m *Result) GetT() string {
	if m != nil {
		return m.T
	}
	return ""
}

func init() {
	proto.RegisterType((*Ping)(nil), "rpc.Ping")
	proto.RegisterType((*Pong)(nil), "rpc.Pong")
	proto.RegisterType((*Job)(nil), "rpc.Job")
	proto.RegisterType((*Job_Header)(nil), "rpc.Job.Header")
	proto.RegisterType((*Result)(nil), "rpc.Result")
	proto.RegisterMapType((map[string]string)(nil), "rpc.Result.HotMapEntry")
}

func init() { proto.RegisterFile("job.proto", fileDescriptor_f32c477d91a04ead) }

var fileDescriptor_f32c477d91a04ead = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xcd, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xbb, 0xf9, 0xd2, 0x4c, 0x04, 0x65, 0x10, 0x0c, 0xb9, 0xb4, 0xe4, 0x54, 0x41, 0x22,
	0xd4, 0x8b, 0x7a, 0x93, 0x22, 0xd4, 0x8a, 0x20, 0xa1, 0xf4, 0xbe, 0x89, 0x4b, 0x5a, 0x13, 0x77,
	0xc3, 0x36, 0x55, 0x72, 0xf5, 0x2f, 0x97, 0xfd, 0x08, 0xe6, 0xf6, 0xf6, 0xfd, 0x66, 0xe7, 0xed,
	0xce, 0x40, 0xf8, 0x29, 0x8a, 0xac, 0x95, 0xa2, 0x13, 0xe8, 0xca, 0xb6, 0x4c, 0x13, 0xf0, 0xde,
	0xf7, 0xbc, 0x42, 0x04, 0xaf, 0xdd, 0xf3, 0x2a, 0x26, 0x33, 0x32, 0x0f, 0x73, 0xad, 0x35, 0x13,
	0x96, 0x89, 0x11, 0x13, 0xbc, 0x4a, 0x25, 0xb8, 0x6b, 0x51, 0x28, 0xc4, 0xe9, 0x17, 0x1b, 0x90,
	0xd2, 0x78, 0x0d, 0x27, 0x3b, 0x46, 0x3f, 0x98, 0x3c, 0xc4, 0xce, 0xcc, 0x9d, 0x47, 0x8b, 0xf3,
	0x4c, 0xb6, 0x65, 0xb6, 0x16, 0x45, 0xb6, 0xd2, 0x7e, 0x3e, 0xf0, 0xe4, 0x06, 0x02, 0x63, 0xe1,
	0x05, 0xb8, 0xaf, 0xac, 0xb7, 0x7d, 0x94, 0x54, 0xce, 0x96, 0x36, 0xb1, 0x63, 0x9c, 0x2d, 0x6d,
	0xd2, 0x5f, 0x02, 0x41, 0xce, 0x0e, 0xc7, 0xa6, 0xc3, 0x5b, 0x08, 0x56, 0xa2, 0x7b, 0xa3, 0x6d,
	0x4c, 0x74, 0xc4, 0x95, 0x8e, 0x30, 0x30, 0x33, 0xe4, 0x99, 0x77, 0xb2, 0xcf, 0x6d, 0x19, 0x9e,
	0x01, 0xd9, 0xd8, 0x5e, 0x64, 0x93, 0x3c, 0x40, 0x34, 0x2a, 0x52, 0x51, 0xf5, 0x7f, 0x78, 0xcd,
	0x7a, 0xbc, 0x04, 0xff, 0x9b, 0x36, 0x47, 0x66, 0xaf, 0x98, 0xc3, 0xa3, 0x73, 0x4f, 0x16, 0x2f,
	0xe0, 0x3f, 0x55, 0x8c, 0x77, 0x38, 0x05, 0x6f, 0x29, 0xe9, 0x0f, 0x9e, 0x0e, 0xbf, 0x4b, 0xa2,
	0xd1, 0x23, 0xd2, 0x09, 0x4e, 0xc1, 0x5f, 0xee, 0x58, 0x59, 0x63, 0xa8, 0x7d, 0x35, 0xe6, 0xc4,
	0x4a, 0x35, 0xc1, 0x49, 0x11, 0xe8, 0x3d, 0xdc, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xb8,
	0x6e, 0x21, 0x94, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	Craw(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Result, error)
	Check(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Craw(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/rpc.Agent/Craw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Check(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/rpc.Agent/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	Craw(context.Context, *Job) (*Result, error)
	Check(context.Context, *Ping) (*Pong, error)
}

// UnimplementedAgentServer can be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (*UnimplementedAgentServer) Craw(ctx context.Context, req *Job) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Craw not implemented")
}
func (*UnimplementedAgentServer) Check(ctx context.Context, req *Ping) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_Craw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Craw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Agent/Craw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Craw(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Agent/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Check(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Craw",
			Handler:    _Agent_Craw_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _Agent_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job.proto",
}
